<?php
$count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
$total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
$cart = Mage::getModel('checkout/cart')->getQuote();
if ($count == null  ){
    $count = 0;
}
?>

<div class="cart module13">
   <div class="module13__underlay"></div>
   <div class="cart__popin module13__popin">
      <a class="module13__close"></a>

      <h3 class="cart__title">Mon panier</h3>
      <ul class="cart__content">
      <?php if($count > 0){ ?>
    
        <?php foreach ($cart->getAllItems() as $item): ?>
         <li class="cart__content-product">
            <div class="cart__content-product-image" style="background-image: url('<?php echo  $item->getProduct()->getImageUrl('small_image'); ?>');"></div>
            <div class="cart__content-product-details">
               <div class="cart__content-product-infos">
                  <h3 class="cart__content-product-title">
                  <?php  echo $productName = $item->getProduct()->getName(); ?>
                  </h3>
                  <p class="cart__content-product-sc text-small">
                     Taille : M
                  </p>
                  <p class="cart__content-product-sc text-small">
                     Colori: Azure
                  </p>
               </div>
               <div class="cart__content-product-price">
                  <a class="cart__content-product-delete" href="">
                     supprimer
                  </a>
                  <p class="cart__content-product-cost">
                     <b> <?php echo $productPrice = $item->getProduct()->getPrice(); ?></b>€ TTC
                  </p>
               </div>
            </div>
         </li>
      <?php endforeach;
       } else{?> <p>Aucun produit dans le panier <?php } ?>
      </ul>
      

      <div class="cart__details">
         <h3 class="cart__details-title">Détails du panier</h3>
         <div class="cart__details-content">
            <ul class="cart__details-totals">
               <li>
                  <p class="cart__details-totals-label">
                     Total du panier (HT)
                  </p>
                  <p class="cart__details-totals-price">
                  <?= $total -12 ?> €
                  </p>
               </li>
               <li>
                  <p class="cart__details-totals-label">
                     Frais de port
                  </p>
                  <p class="cart__details-totals-price">
                     12 €
                  </p>
               </li>
               <li>
                  <p class="cart__details-totals-label">
                     TVA
                  </p>
                  <p class="cart__details-totals-price">
                  <?= $total ?>€
                  </p>
               </li>
            </ul>
            <input class="cart__details-promo" type="text" placeholder="Ajouter un code promo">
         </div>
      </div>

      <div class="cart__pay">
         <div class="cart__pay-total">
            <p class="cart__pay-total-label">
               <b>Total</b> (TTC)
            </p>
            <p class="cart__pay-total-price">
               <?= $total ?> €
            </p>
         </div>
         <a class="cart__pay-link button button-black" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
            Accéder au paiement
         </a>
      </div>

   </div>
</div>

