<?php
$count = $this->helper('checkout/cart')->getSummaryCount();  //get total items in cart
$total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price
?>

<div class="cart module13">
   <div class="module13__underlay"></div>
   <div class="cart__popin module13__popin">
      <a class="module13__close"></a>

      <h3 class="cart__title">Mon panier</h3>

      <ul class="cart__content">

         <li class="cart__content-product">
            <div class="cart__content-product-image"></div>
            <div class="cart__content-product-details">
               <div class="cart__content-product-infos">
                  <h3 class="cart__content-product-title">
                     Chemise Silk
                  </h3>
                  <p class="cart__content-product-sc text-small">
                     Taille : M
                  </p>
                  <p class="cart__content-product-sc text-small">
                     Colori: Azure
                  </p>
               </div>
               <div class="cart__content-product-price">
                  <a class="cart__content-product-delete">
                     supprimer
                  </a>
                  <p class="cart__content-product-cost">
                     <b>190€</b> TTC
                  </p>
               </div>
            </div>
         </li>
         <li class="cart__content-product">
            <div class="cart__content-product-image"></div>
            <div class="cart__content-product-details">
               <div class="cart__content-product-infos">
                  <h3 class="cart__content-product-title">
                     Chemise Silk
                  </h3>
                  <p class="cart__content-product-sc text-small">
                     Taille : M
                  </p>
                  <p class="cart__content-product-sc text-small">
                     Colori: Azure
                  </p>
               </div>
               <div class="cart__content-product-price">
                  <a class="cart__content-product-delete">
                     supprimer
                  </a>
                  <p class="cart__content-product-cost">
                     <b>190€</b> TTC
                  </p>
               </div>
            </div>
         </li>
         <li class="cart__content-product">
            <div class="cart__content-product-image"></div>
            <div class="cart__content-product-details">
               <div class="cart__content-product-infos">
                  <h3 class="cart__content-product-title">
                     Chemise Silk
                  </h3>
                  <p class="cart__content-product-sc text-small">
                     Taille : M
                  </p>
                  <p class="cart__content-product-sc text-small">
                     Colori: Azure
                  </p>
               </div>
               <div class="cart__content-product-price">
                  <a class="cart__content-product-delete">
                     supprimer
                  </a>
                  <p class="cart__content-product-cost">
                     <b>190€</b> TTC
                  </p>
               </div>
            </div>
         </li>
         <li class="cart__content-product">
            <div class="cart__content-product-image"></div>
            <div class="cart__content-product-details">
               <div class="cart__content-product-infos">
                  <h3 class="cart__content-product-title">
                     Chemise Silk
                  </h3>
                  <p class="cart__content-product-sc text-small">
                     Taille : M
                  </p>
                  <p class="cart__content-product-sc text-small">
                     Colori: Azure
                  </p>
               </div>
               <div class="cart__content-product-price">
                  <a class="cart__content-product-delete">
                     supprimer
                  </a>
                  <p class="cart__content-product-cost">
                     <b>190€</b> TTC
                  </p>
               </div>
            </div>
         </li>

      </ul>

      <div class="cart__details">
         <h3 class="cart__details-title">Détails du panier</h3>
         <div class="cart__details-content">
            <ul class="cart__details-totals">
               <li>
                  <p class="cart__details-totals-label">
                     Total du panier (HT)
                  </p>
                  <p class="cart__details-totals-price">
                     570 €
                  </p>
               </li>
               <li>
                  <p class="cart__details-totals-label">
                     Frais de port
                  </p>
                  <p class="cart__details-totals-price">
                     12 €
                  </p>
               </li>
               <li>
                  <p class="cart__details-totals-label">
                     TVA
                  </p>
                  <p class="cart__details-totals-price">
                     31,72 €
                  </p>
               </li>
            </ul>
            <input class="cart__details-promo" type="text" placeholder="Ajouter un code promo">
         </div>
      </div>

      <div class="cart__pay">
         <div class="cart__pay-total">
            <p class="cart__pay-total-label">
               <b>Total</b> (TTC)
            </p>
            <p class="cart__pay-total-price">
               <?= $total ?>
            </p>
         </div>
         <a class="cart__pay-link button button-black" href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>">
            Accéder au paiement
         </a>
      </div>

   </div>
</div>

