
 <div class="module13__overlay"></div>
 <div class="subscribe module13">
         <div class="module13__underlay"></div>
         <div class="subscribe__popin module13__popin">
            <a class="module13__close"></a>
            <img class="subscribe__logo" src="assets/svg/logo_small.svg" />
            <div class="subscribe__content">
               <h3 class="subscribe__content-title">
                  Restez au courant des dernières actualités.
               </h3>
               <p class="subscribe__content-text text">
                  Inscrivez-vous à la newsletter et soyez informés de toutes les actualités liées à Silkani.
               </p>
               <input type="text" class="subscribe__content-email" placeholder="Mon Email">
            </div>
         </div>
      </div>
