<div class="register module13">
   <div class="module13__underlay"></div>
   <div class="register__popin module13__popin">
      <a class="module13__close"></a>
      <div class="register__login">
         <h3 class="register__login-title">S'identifier</h3>
         <p class="register__login-text text-small">
            Connectez-vous à l'aide de vos identifiants pour accéder à votre compte.
         </p>
         <form class="register__login-form">
            <input type="text" placeholder="Email">
            <input type="text" placeholder="Mot de passe">
            <input type="submit" value="Se connecter">
         </form>
      </div>
      <div class="register__signup">
         <h3 class="register__signup-title">Nouveau client</h3>
         <p class="register__signup-text text-small">
            En créant un compte, vous pourrez passer commande plus rapidement, ajouter plusieurs adresses de livraison, suivre vos commandes ou consulter l'historique de vos achats.
         </p>
         <a class="register__signup-link submit-white">S'inscrire</a>
      </div>
   </div>
</div>

<div class="signup module13">
   <div class="module13__underlay"></div>
   <div class="signup__popin module13__popin">
      <a class="module13__close"></a>
      <div class="signup__intro">
         <h3 class="signup__intro-title">S'inscrire</h3>
         <p class="signup__intro-text text-small">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
         </p>
      </div>
      <form class="signup__form">
         <div class="signup__form-left">
            <select name="color">
               <option value="" disabled selected>Sexe</option>
               <option value="Femme">Femme</option>
               <option value="Homme">Homme</option>
               <option value="Autre">Autre</option>
            </select>
            <input type="text" placeholder="Nom">
            <input type="text" placeholder="Adresse Email">
         </div>
         <div class="signup__form-right">
            <input type="text" placeholder="Prénom">
            <input type="text" placeholder="Mot de passe">
         </div>
      </form>
      <div class="signup__send">
         <input type="submit" value="S'inscrire">
         <p class="signup__send-connect text-small">
            Vous avez déjà un compte ? <a class="signup__send-connect-link">Connectez-vous</a>
         </p>
      </div>
   </div>
</div>