<div class="page13 collection">

         <div class="collection__header">
            <div class="collection__header-content">
               <p class="collection__header-text">Collection</p>
               <h1 class="collection__header-title title">
                  Silkani
               </h1>
            </div>
         </div>

         <div class="collection__filters">
            <div class="collection__filters-content">
               <a class="collection__filters-button text-small">Filtrer</a>
               <form>
                  <select class="collection__filters-single" name="collection">
                     <option value="" disabled selected>Collection</option>
                     <option value="Homme">Autumn/Hiver 2018</option>
                     <option value="Femme">Silk</option>
                  </select>
                  <select class="collection__filters-single" name="color">
                     <option value="" disabled selected>Couleur</option>
                     <option value="Rouge">Rouge</option>
                     <option value="Bleu">Bleu</option>
                     <option value="Vert">Vert</option>
                  </select>
                  <select class="collection__filters-single" name="creator">
                     <option value="" disabled selected>Créateur</option>
                     <option value="Jean">Jean</option>
                     <option value="Louis">Louis</option>
                     <option value="David">David</option>
                  </select>
               </form>
            </div>
         </div>

         <div class="collection__gallery">
            <div class="collection__gallery-content">

               <div class="collection__gallery-single">
                  <div class="collection__gallery-single-imgbox">
                     <a class="collection__gallery-single-image"></a>
                  </div>
                  <h3 class="collection__gallery-single-name"><a>Robe Violeta</a></h3>
                  <p class="collection__gallery-single-price">350€</p>
               </div>
               <div class="collection__gallery-single">
                  <div class="collection__gallery-single-imgbox">
                     <a class="collection__gallery-single-image"></a>
                  </div>
                  <h3 class="collection__gallery-single-name"><a>Robe Violeta</a></h3>
                  <p class="collection__gallery-single-price">350€</p>
               </div>
               <div class="collection__gallery-single">
                  <div class="collection__gallery-single-imgbox">
                     <a class="collection__gallery-single-image"></a>
                  </div>
                  <h3 class="collection__gallery-single-name"><a>Robe Violeta</a></h3>
                  <p class="collection__gallery-single-price">350€</p>
               </div>
               <div class="collection__gallery-single">
                  <div class="collection__gallery-single-imgbox">
                     <a class="collection__gallery-single-image"></a>
                  </div>
                  <h3 class="collection__gallery-single-name"><a>Robe Violeta</a></h3>
                  <p class="collection__gallery-single-price">350€</p>
               </div>
               <div class="collection__gallery-single">
                  <div class="collection__gallery-single-imgbox">
                     <a class="collection__gallery-single-image"></a>
                  </div>
                  <h3 class="collection__gallery-single-name"><a>Robe Violeta</a></h3>
                  <p class="collection__gallery-single-price">350€</p>
               </div>
               <div class="collection__gallery-single">
                  <div class="collection__gallery-single-imgbox">
                     <a class="collection__gallery-single-image"></a>
                  </div>
                  <h3 class="collection__gallery-single-name"><a>Robe Violeta</a></h3>
                  <p class="collection__gallery-single-price">350€</p>
               </div>

            </div>
         </div>

      </div>