
<?php 
$category = Mage::getModel('catalog/category')
    ->getCollection()
    ->addAttributeToSort('created_at', 'desc');
    $collection->getSelect()->limit(1);
    echo $latestItemId = $collection->getLastItem()->getData();
?>


<div class="full-section home__section home__newcollection">
<div class="home__section-image"></div>
<div class="home__section-content">
<h2 class="home__section-title title">NOUVELLE<br />COLLECTION</h2>
<p class="home__section-text text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rhoncus lacus at gravida finibus. In sit amet imperdiet eros, at porta risus. Curabitur neque nibh, suscipit tempus pellentesque a, convallis sed nisi.</p>
<a class="home__section-button button button-black">Call to action</a></div>
</div>