<div class="home__section home__articles">
<div class="home__articles-content">
<h2 class="home__articles-title title">Articles</h2>
<p class="home_articles-text text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam rhoncus lacus at gravida finibus. In sit amet imperdiet eros, at porta risus.</p>
</div>
<div class="home__articles-list-container">



<?php function CallAPI($method, $url, $data = false)
{
    $curl = curl_init();

    switch ($method)
    {
        case "POST":
            curl_setopt($curl, CURLOPT_POST, 1);

            if ($data)
                curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
            break;
        case "PUT":
            curl_setopt($curl, CURLOPT_PUT, 1);
            break;
        default:
            if ($data)
                $url = sprintf("%s?%s", $url, http_build_query($data));
    }

    // Optional Authentication:
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($curl, CURLOPT_USERPWD, "username:password");

    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

    $result = curl_exec($curl);

    curl_close($curl);

    return $result;
}
?>

<div class="home__articles-list">
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="assets/svg/arrow-right-icon.svg" /></a></div>
</div>
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="assets/svg/arrow-right-icon.svg" /></a></div>
</div>
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="assets/svg/arrow-right-icon.svg" /></a></div>
</div>
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="assets/svg/arrow-right-icon.svg" /></a></div>
</div>
</div>
</div>
<div class="home__articles-nav"><img class="home__articles-nav-arrow" src="assets/svg/previous-icon.svg" /> <img class="home__articles-nav-arrow" src="assets/svg/next-icon.svg" /></div>
</div>
</div>
