<div class="home__section home__articles">
<div class="home__articles-content">

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('articles')->toHtml();  ?>

</div>
<div class="home__articles-list-container">



<?php //  Initiate curl
$id=1515582298020;
$url= 'https://medium.com/@'.$id.'/latest?format=json';
$ch = curl_init();
// Disable SSL verification
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
// Will return the response, if false it print the response
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// Set the url
curl_setopt($ch, CURLOPT_URL,$url);
// Execute
$result=curl_exec($ch);
// Closing
curl_close($ch);

$result = str_replace('])}while(1);</x>', "", $result, $resultOK);
// Will dump a beauty json :3

?>


<div class="home__articles-list" id="articles" data-content='<?php echo $result ?>'>
<script type="text/javascript">

var data = document.getElementById('articles').getAttribute('data-content');

var dataJSON = JSON.parse(data);
console.log(dataJSON);
</script>


<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="<?php echo $this->getSkinUrl('images/arrow_right_icon.svg') ?>" /></a></div>
</div>
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="<?php echo $this->getSkinUrl('images/arrow_right_icon.svg') ?>" /></a></div>
</div>
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="<?php echo $this->getSkinUrl('images/arrow_right_icon.svg') ?>" /></a></div>
</div>
<div class="home__articles-list-item">
<div class="home__articles-list-image"></div>
<div class="home__articles-list-content">
<h3 class="home__articles-list-title">Titre de l'article</h3>
<p class="home__articles-list-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<a class="home__articles-list-button button">Lire plus<img class="button-icon" src="<?php echo $this->getSkinUrl('images/arrow_right_icon.svg') ?>" /></a></div>
</div>
</div>
</div>
<div class="home__articles-nav"><img class="home__articles-nav-arrow" src="<?php echo $this->getSkinUrl('images/arrow_right_icon.svg') ?>" /> <img class="home__articles-nav-arrow" src="<?php echo $this->getSkinUrl('images/next_icon.svg') ?>" /></div>
</div>
</div>
