<div class="home__section home__articles">
<div class="home__articles-content">

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('articles')->toHtml();  ?>

</div>
<div class="home__articles-list-container">



<?php //  Initiate curl
$id=1515582298020;
$url= 'https://medium.com/@'.$id.'/latest?format=json';
$ch = curl_init();
// Disable SSL verification
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
// Will return the response, if false it print the response
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// Set the url
curl_setopt($ch, CURLOPT_URL,$url);
// Execute
$result=curl_exec($ch);
// Closing
curl_close($ch);

$result = str_replace('])}while(1);</x>', "", $result, $resultOK);
// Will dump a beauty json :3

?>


<div class="home__articles-list" id="articles" data-content='<?php echo $result ?>'>
<script type="text/javascript">

var data = document.getElementById('articles').getAttribute('data-content');

var dataJSON = JSON.parse(data);
var articles = dataJSON.payload.references.Post;
articleList = [];
for(var k in articles) articleList.push(k);
var arrowURL = "http://46.20.121.65/skin/frontend/theme13/default/images/arrow_right_icon.svg";
var html = ""
console.log(articleList);

for(let i = 0; i < articleList.length; i++){
    let img = articleList[i].virtuals.previewImage;
    let url = "https://medium.com/@1515582298020/"+articleList[i].uniqueSlug;
    let title = articleList[i].title;
    let desc = articleList[i].content.subtitle;
    html += '<div class="home__articles-list-item">';
    html += '<div class="home__articles-list-image" style="background-image: url("https://cdn-images-1.medium.com/max/1600/'+img+'")"></div>';
    html +='<div class="home__articles-list-content">';
    html += '<h3 class="home__articles-list-title">'+title+'</h3>';
    html += '<p class="home__articles-list-text">'+desc+'</p>';
    html += '<a class="home__articles-list-button button" href="'+url+'">Lire plus<img class="button-icon" src="'+arrowURL+'" /></a></div></div>'
}
console.log(html);

document.getElementById('articles').innerHTML = html;
</script>



</div>